@table = appuser
@id = 1
@body = {"with": ["account", "role"]}

GET http://blog.api/init

###

GET http://blog.api/{{table}}

###
GET http://blog.api/{{table}}/{{id}}

###
POST http://blog.api/{{table}}
Content-Type: application/json

{{body}}

###
POST http://blog.api/{{table}}/0
Content-Type: application/json

{{body}}

###
POST http://blog.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PUT http://blog.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PATCH http://blog.api/{{table}}/{{id}}

###
DELETE http://blog.api/{{table}}/{{id}}
