@table = tag
@id = 1
@body = {"with": [{"article":"article_tag"}] }

### init controllers
GET http://blog.api/init

### get all
GET http://blog.api/{{table}}

### get one
GET http://blog.api/{{table}}/{{id}}

### 
POST http://blog.api/{{table}}
Content-Type: application/json

{{body}}

### get all with relations
POST http://blog.api/{{table}}/0
Content-Type: application/json

{{body}}

### get one with relations
POST http://blog.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PUT http://blog.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PATCH http://blog.api/{{table}}/{{id}}

###
DELETE http://blog.api/{{table}}/{{id}}
